# Site settings
baseURL = "https://kateryna-tarasova.netlify.app"
languageCode = "en-us"
title = "Portfolio website for Kateryna Tarasova"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Kateryna Tarasova"
  description = "Portfolio of past projects"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Kateryna"
    subtitle = "Tarasova"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

#    [[params.navigation.links]]
#      name = "Blogs"
#      url = "blogs"

#    [[params.navigation.links]]
#      name = "Generic Blog"
#      url = "blogs/ipsum"

#    [[params.navigation.links]]
#      name = "Elements"
#      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
#    [[params.navigation.button1]]
#      name = "Get Started"
#      url = "blogs"

    # Button Style 2
#    [[params.navigation.button2]]
#      name = "Log In"
#      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Kateryna"
    subtitle = "I am an electrical and electronic engineering graduate passionate about finance"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "CV"
      subtitle = "Education and Work Experience"
      image = "resume.jpg"
      url = "blogs/CV_Kateryna_Tarasova.pdf"

    [[params.tiles.showcase]]
      title = "COVID 2019"
      subtitle = "Exploring COVID statistics"
      image = "covidimage.png"
      url = "blogs/covid"

    [[params.tiles.showcase]]
      title = "Does America Approve of Trump"
      subtitle = "Trump vs Hillary"
      image = "trump.jpg"
      url = "blogs/trump"

    [[params.tiles.showcase]]
      title = "Twitter usage by education level"
      subtitle = "Can we estimate the *population* proportion of Twitter users by education level in 2016?"
      image = "twitter.jpg"
      url = "blogs/twitter"

    [[params.tiles.showcase]]
      title = "Yield Curve Inversion"
      subtitle = "Plot the yield curves since 1999 to see when the yield curves flatten"
      image = "fin.jpeg"
      url = "blogs/yieldcurve"

    [[params.tiles.showcase]]
      title = "Hong Kong Airbnb Analysis"
      subtitle = "How much will 4 nights in Hong Kong cost?"
      image = "hk.jpg"
      url = "blogs/hk"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About me"
    subtitle = """ 
    I am a Masters in Financial Analysis student at London Business School. 
    Recently I have graduated with an MEng degree in Electrical and Electronic Engineering from Imperial College London. Last summer I interned at J.P.Morgan as an Investment Banking Summer Analyst. Originally from Ukraine, I moved to the UK because of my passion for sciences and a desire to learn. My interests include finance, investment banking, machine learning, electrical engineering and robotics. Between 2018 annd 2019, I was the first female President of the Imperial College Finance Society - the largest organisation at Imperial College and one of the largest student socities in the UK. I am also a co-organiser fo the largest student-led fintech conference in Europe - London Fintech Conference 2019. """
    buttonText = "See my engineering and robotics projects"
    url = "https://tarasova.co.uk"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "yekaterina.tarasova@gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44(0)7511503002"

    [[params.contact.address]]
    title = "Address"
    street = "London Business School"
    city = "London, NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons
 #   [[params.footer.social]]
 #     icon = "fa-twitter"
 #     url= "https://www.twitter.com"
 #     label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/CatherineS.Tarasova/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/yekaterina_tarasova/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/katerina1414/"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/katerina-tarasova/"
      label = "LinkedIn"

 #   [[params.footer.quicklinks]]
 #     text = "Design: "
 #     url= "https://www.html5up.net"
 #     alt = "HTML5 UP"
